# Generated by Django 4.0.4 on 2022-05-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vacuna', models.CharField(max_length=40)),
                ('vacunatorio', models.CharField(max_length=40)),
            ],
        ),
    ]
