# Generated by Django 4.0.4 on 2022-05-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='usuario_a_vacunar',
            field=models.CharField(default=11111111, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
