# Generated by Django 4.0.4 on 2022-05-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0002_turno_hora_turno_usuario_a_vacunar_alter_turno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(choices=[('Zona municipalidad', '51 e/ 10  y 11 nro 770'), ('Zona cementerio', '138 e/ 73 y 74 nro 2035'), ('Zona terminal de omnibus', '3 e/ 41 y 42 nro 480')], max_length=30),
        ),
    ]
