# Generated by Django 4.0.4 on 2022-06-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0004_codigos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('Completo', 'Completo'), ('Incompleto', 'Incompleto')], default='Pendiente', max_length=40),
        ),
    ]
