# Generated by Django 4.0.4 on 2022-06-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0005_vacunador_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunador',
            name='apellido',
            field=models.CharField(default='Abc', max_length=30),
        ),
        migrations.AddField(
            model_name='vacunador',
            name='contraseña',
            field=models.CharField(default='hola1234567', max_length=60),
        ),
        migrations.AddField(
            model_name='vacunador',
            name='email',
            field=models.EmailField(default='Abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='vacunador',
            name='nombre',
            field=models.CharField(default='Abc', max_length=30),
        ),
        migrations.AddField(
            model_name='vacunador',
            name='vacunatorio',
            field=models.CharField(choices=[('Zona municipalidad', '51 e/ 10  y 11 nro 770'), ('Zona cementerio', '138 e/ 73 y 74 nro 2035'), ('Zona terminal de omnibus', '3 e/ 41 y 42 nro 480')], default='Zona municipalidad', max_length=30),
        ),
    ]
