# Generated by Django 4.0.4 on 2022-06-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0007_historialcovid_historialfiebrea_historialgripe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcovid',
            name='fecha_primeradosis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialcovid',
            name='fecha_segundadosis',
            field=models.DateField(blank=True, null=True),
        ),
    ]
