# Generated by Django 4.0.4 on 2022-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0009_turno_observaciones_alter_turno_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=8)),
                ('vacuna', models.CharField(max_length=20)),
                ('cantidad_dosis_covid', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_primeradosis_covid', models.DateField(blank=True, null=True)),
                ('fecha_segundadosis_covid', models.DateField(blank=True, null=True)),
                ('fecha_aplicacion_fiebre_a', models.DateField(blank=True, null=True)),
                ('fecha_aplicacion_gripe', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historialfiebrea',
            name='si_o_no',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('Completo', 'Completo'), ('Incompleto', 'Incompleto')], max_length=40),
        ),
        migrations.AlterField(
            model_name='turno',
            name='vacunatorio',
            field=models.CharField(choices=[('Zona municipalidad', '51 e/ 10  y 11 nro 770'), ('Zona cementerio', '138 e/ 73 y 74 nro 2035'), ('Zona terminal de omnibus', '3 e/ 41 y 42 nro 480')], max_length=40),
        ),
    ]
