# Generated by Django 4.0.4 on 2022-06-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0011_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcovid',
            name='vacuna_externa_covid_dosis_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historialcovid',
            name='vacuna_externa_covid_dosis_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historialfiebrea',
            name='vacuna_externa_fiebre',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historialgripe',
            name='vacuna_externa_gripe',
            field=models.BooleanField(null=True),
        ),
    ]
