# Generated by Django 4.0.4 on 2022-06-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0012_historialcovid_vacuna_externa_covid_dosis_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreVacunador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacunatorio', models.CharField(choices=[('Zona municipalidad', '51 e/ 10  y 11 nro 770'), ('Zona cementerio', '138 e/ 73 y 74 nro 2035'), ('Zona terminal de omnibus', '3 e/ 41 y 42 nro 480')], max_length=30)),
                ('nuevo_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='historialcovid',
            name='fecha_primeradosis',
        ),
        migrations.RemoveField(
            model_name='historialcovid',
            name='fecha_segundadosis',
        ),
        migrations.RemoveField(
            model_name='historialcovid',
            name='vacuna_externa_covid_dosis_1',
        ),
        migrations.RemoveField(
            model_name='historialcovid',
            name='vacuna_externa_covid_dosis_2',
        ),
    ]
