# Generated by Django 4.0.4 on 2022-06-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0013_nombrevacunador_vacunatorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vacunador',
            name='vacunatorio',
            field=models.CharField(max_length=30),
        ),
    ]
