# Generated by Django 4.0.4 on 2022-06-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0014_alter_usuario_direccion_alter_vacunador_vacunatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='vacunatorio',
            field=models.CharField(max_length=40),
        ),
    ]
