# Generated by Django 4.0.4 on 2022-07-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0015_alter_turno_vacunatorio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialVacunacion',
        ),
    ]
