# Generated by Django 4.0.4 on 2022-07-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0017_vacunatorio_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunatorio',
            name='calle',
            field=models.CharField(max_length=20),
        ),
    ]
