# Generated by Django 4.0.4 on 2022-07-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0018_alter_vacunatorio_calle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunatorio',
            name='calle',
        ),
        migrations.AddField(
            model_name='historialcovid',
            name='apellido_usuario',
            field=models.CharField(default='Apellido', max_length=50),
        ),
        migrations.AddField(
            model_name='historialcovid',
            name='nombre_usuario',
            field=models.CharField(default='Nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='historialfiebrea',
            name='apellido_usuario',
            field=models.CharField(default='Apellido', max_length=50),
        ),
        migrations.AddField(
            model_name='historialfiebrea',
            name='nombre_usuario',
            field=models.CharField(default='Nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='historialgripe',
            name='apellido_usuario',
            field=models.CharField(default='Apellido', max_length=50),
        ),
        migrations.AddField(
            model_name='historialgripe',
            name='nombre_usuario',
            field=models.CharField(default='Nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='turno',
            name='apellido_usuario',
            field=models.CharField(default='Apellido', max_length=50),
        ),
        migrations.AddField(
            model_name='turno',
            name='nombre_usuario',
            field=models.CharField(default='Nombre', max_length=50),
        ),
    ]
