# Generated by Django 4.0.4 on 2022-07-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0019_remove_vacunatorio_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcovid',
            name='apellido_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historialcovid',
            name='nombre_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historialfiebrea',
            name='apellido_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historialfiebrea',
            name='nombre_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historialgripe',
            name='apellido_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historialgripe',
            name='nombre_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='turno',
            name='apellido_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nombre_usuario',
            field=models.CharField(max_length=50),
        ),
    ]
