# Generated by Django 4.0.4 on 2022-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0020_alter_historialcovid_apellido_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='dosis',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
