# Generated by Django 4.0.4 on 2022-07-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gestion_usuarios', '0022_alter_turno_dosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
